#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/prepare_remote.sh [options]

Prepare a fresh remote machine for DiffusionBlocks experiments.

Options:
  --scratch-dir DIR    Base directory for logs, W&B files, and HF caches.
                       Default: $DIFFUSIONBLOCKS_SCRATCH or ~/scratch/diffusionblocks
  --no-install-uv      Fail if uv is not already installed.
  --no-sync            Skip uv sync --frozen.
  --no-link-logs       Do not symlink ./logs to the scratch logs directory.
  -h, --help           Show this help.

After this script finishes, run:
  source .remote.env
  uv run huggingface-cli login
  uv run wandb login
EOF
}

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRATCH_DIR="${DIFFUSIONBLOCKS_SCRATCH:-"$HOME/scratch/diffusionblocks"}"
INSTALL_UV=1
RUN_SYNC=1
LINK_LOGS=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --scratch-dir)
      SCRATCH_DIR="$2"
      shift 2
      ;;
    --no-install-uv)
      INSTALL_UV=0
      shift
      ;;
    --no-sync)
      RUN_SYNC=0
      shift
      ;;
    --no-link-logs)
      LINK_LOGS=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

cd "$PROJECT_DIR"

if ! command -v uv >/dev/null 2>&1; then
  if [[ "$INSTALL_UV" -ne 1 ]]; then
    echo "uv is not installed. Re-run without --no-install-uv or install uv first." >&2
    exit 1
  fi
  if ! command -v curl >/dev/null 2>&1; then
    echo "curl is required to install uv automatically." >&2
    exit 1
  fi
  echo "Installing uv..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
fi

if ! command -v uv >/dev/null 2>&1; then
  echo "uv installation did not put uv on PATH. Add it to PATH and re-run." >&2
  exit 1
fi

LOGS_DIR="$SCRATCH_DIR/logs"
HF_HOME_DIR="$SCRATCH_DIR/hf-cache"
HF_DATASETS_DIR="$HF_HOME_DIR/datasets"
WANDB_DIR="$SCRATCH_DIR/wandb"

mkdir -p "$LOGS_DIR" "$HF_DATASETS_DIR" "$WANDB_DIR"

ENV_FILE="$PROJECT_DIR/.remote.env"
{
  echo "# Source this before running experiments on this machine."
  echo "# Generated by scripts/prepare_remote.sh"
  printf 'export DIFFUSIONBLOCKS_SCRATCH=%q\n' "$SCRATCH_DIR"
  printf 'export HF_HOME=%q\n' "$HF_HOME_DIR"
  printf 'export HF_DATASETS_CACHE=%q\n' "$HF_DATASETS_DIR"
  printf 'export WANDB_DIR=%q\n' "$WANDB_DIR"
  printf 'export HF_HUB_ENABLE_HF_TRANSFER=1\n'
} > "$ENV_FILE"

if [[ "$LINK_LOGS" -eq 1 ]]; then
  if [[ -L logs ]]; then
    ln -sfn "$LOGS_DIR" logs
  elif [[ -d logs ]] && [[ -z "$(find logs -mindepth 1 -maxdepth 1 -print -quit)" ]]; then
    rmdir logs
    ln -s "$LOGS_DIR" logs
  elif [[ -e logs ]]; then
    echo "Leaving existing ./logs in place because it is not an empty directory or symlink."
    echo "Remote logs directory is still available at: $LOGS_DIR"
  else
    ln -s "$LOGS_DIR" logs
  fi
fi

if [[ "$RUN_SYNC" -eq 1 ]]; then
  uv sync --frozen
fi

cat <<EOF

Remote machine is prepared.

Project:      $PROJECT_DIR
Scratch:      $SCRATCH_DIR
Logs:         $LOGS_DIR
HF cache:     $HF_HOME_DIR
W&B dir:      $WANDB_DIR
Environment: $ENV_FILE

Next:
  source .remote.env
  uv run huggingface-cli login
  uv run wandb login
  uv run main.py train cifar100 --model_type dblock
EOF
